# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

maxEntropyCpp <- function(aw, rs, cs, minError) {
    .Call('unsumnet_maxEntropyCpp', PACKAGE = 'unsumnet', aw, rs, cs, minError)
}

unsumcpp <- function(constraints, target_ne, verbose, maxEdges, noReturn, mct_schedule, hot_time, beta0, betamax, mu0, cooling_rate, max_time, cgmax) {
    .Call('unsumnet_unsumcpp', PACKAGE = 'unsumnet', constraints, target_ne, verbose, maxEdges, noReturn, mct_schedule, hot_time, beta0, betamax, mu0, cooling_rate, max_time, cgmax)
}

